-- ============================================================================
-- data.sql  ·  Catálogo real del Laboratorio Clínico Danimar
-- Esquema del proyecto (tmcategorias / tmexamenes / tmcampos).
-- Reemplaza al data.sql de ejemplo del backend.
-- ============================================================================

-- Usuario de acceso (igual que el de ejemplo)
INSERT INTO tmusuarios (usuario, contrasena_hash) VALUES ('marisolquintero', 'danielita123');

-- Pacientes de ejemplo
INSERT INTO tmpacientes (cedula, nombre_completo) VALUES ('29636040', 'Manuel Torres');
INSERT INTO tmpacientes (cedula, nombre_completo) VALUES ('15774151', 'Michelle Quintero');

-- ===================== CATEGORÍAS =====================
INSERT INTO tmcategorias (id_cat, nombre_cat) VALUES (1, 'Hematología');
INSERT INTO tmcategorias (id_cat, nombre_cat) VALUES (2, 'Otros Exámenes');
INSERT INTO tmcategorias (id_cat, nombre_cat) VALUES (3, 'Misceláneos');
INSERT INTO tmcategorias (id_cat, nombre_cat) VALUES (5, 'Hormonas y Endocrinología');
INSERT INTO tmcategorias (id_cat, nombre_cat) VALUES (6, 'Serología e Inmunología');

-- ===================== EXÁMENES =====================
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (1, 1, 'Hematología Completa', 'HEM-001', 1350.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (2, 1, 'Químico Sanguíneo I', 'HEM-002', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (3, 1, 'Químico Sanguíneo II', 'HEM-003', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (4, 1, 'Frotis de Sangre Periférica', 'HEM-004', 1350.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (5, 1, 'Tipo de Sangre (Carnet)', 'HEM-005', 1800.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (6, 2, 'Uroanálisis', 'OTR-001', 900.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (7, 2, 'Coproanálisis', 'OTR-002', 1440.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (8, 2, 'Antígenos Febriles', 'OTR-003', 2700.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (9, 2, 'Serología de Donante', 'OTR-004', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (10, 2, 'Inmunología', 'OTR-005', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (11, 2, 'Prueba de Embarazo', 'OTR-006', 1800.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (12, 2, 'Cultivo de Orina', 'OTR-007', 6300.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (13, 6, 'Hepatitis A (IgM)', 'SER-001', 1800.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (14, 6, 'Hepatitis B (HBsAg)', 'SER-002', 1530.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (15, 6, 'Hepatitis C', 'SER-003', 1530.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (16, 6, 'Mycoplasma Pneumoniae (IgG)', 'SER-004', 3150.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (17, 5, 'Gonadotropina Coriónica Cuantificada', 'HOR-001', 3150.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (18, 5, 'LH', 'HOR-002', 2700.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (19, 5, 'Progesterona', 'HOR-003', 3600.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (20, 5, 'Prolactina', 'HOR-004', 2700.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (21, 3, 'Frotis de Flujo Vaginal', 'MIS-001', 1800.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (22, 6, 'V.D.R.L. y H.I.V.', 'SER-005', 2880.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (23, 5, 'Insulina', 'HOR-005', 2700.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (24, 3, 'Anti-doping', 'MIS-002', 2700.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (25, 6, 'Serología Dengue', 'SER-006', 2880.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (26, 3, 'Inmunoglobulina E', 'MIS-003', 2700.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (27, 3, 'P.S.A.', 'MIS-004', 5400.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (28, 5, 'Perfil Tiroideo', 'HOR-006', 8100.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (29, 3, 'Eosinófilos en Moco Nasal', 'MIS-005', 1080.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (30, 3, 'Eosinófilos en Sangre', 'MIS-006', 1080.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (31, 6, 'Anti-toxoplasmosis', 'SER-007', 6300.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (32, 6, 'Anti-citomegalovirus', 'SER-008', 2700.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (33, 3, 'Curva de Tolerancia a la Glucosa', 'MIS-007', 5760.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (34, 5, 'Testosterona', 'HOR-007', 6300.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (35, 6, 'Helicobacter Pylori (Suero)', 'SER-009', 3150.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (37, 3, 'Monotest', 'MIS-008', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (38, 6, 'H.I.V. Test-Pack', 'SER-010', 1530.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (39, 5, 'Antitiroideos', 'HOR-008', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (40, 3, 'Baciloscopia Seriada', 'MIS-009', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (41, 6, 'Dengue NS1', 'SER-011', 2880.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (42, 6, 'Hepatitis A (Método Elisa)', 'SER-012', 1800.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (43, 6, 'Helicobacter Pylori en Heces', 'SER-013', 2700.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (44, 5, 'Estradiol', 'HOR-009', 3150.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (45, 5, 'FSH', 'HOR-010', 2700.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (46, 6, 'Machado Guerreiro (Chagas)', 'SER-014', 2700.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (47, 3, 'Antígeno Carcinoembrionario (C.E.A.)', 'MIS-010', 3150.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (48, 3, 'CA 19-9', 'MIS-011', 3150.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (49, 3, 'CA-125', 'MIS-012', 3150.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (50, 3, 'CA 15-3', 'MIS-013', 3150.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (51, 3, 'Alfafetoproteínas', 'MIS-014', 3150.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (52, 5, '17 OH Progesterona', 'HOR-011', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (53, 5, 'DHEA', 'HOR-012', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (54, 5, 'Androstenediona', 'HOR-013', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (55, 6, 'Virus del Epstein Barr (IgM)', 'SER-015', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (56, 5, 'Hemoglobina A1c', 'HOR-014', 3150.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (57, 1, 'Fibrinógeno', 'HEM-006', 1800.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (58, 5, 'TSH Ultra', 'HOR-015', 2700.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (59, 2, 'Microalbuminuria en Orina Parcial', 'OTR-008', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (60, 6, 'Anticuerpos Antinucleares (ANA)', 'SER-016', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (61, 3, 'Lactato Deshidrogenasa (LDH)', 'MIS-015', 1800.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (62, 6, 'Hepatitis B Anti-HBs (Anticuerpos)', 'SER-017', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (63, 6, 'Anticuerpos IgG Anti Varicela Zoster', 'SER-018', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (64, 1, 'Dímero-D', 'HEM-007', 0.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (65, 6, 'Herpes I y II', 'SER-019', 3150.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (66, 3, 'Creatinfosfoquinasa (CPK)', 'MIS-016', 2700.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (67, 3, 'Vitamina D', 'MIS-017', 6300.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (68, 5, 'Cortisol', 'HOR-016', 3600.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (69, 6, 'Mycoplasma Pneumoniae (IgM)', 'SER-020', 3150.00);
INSERT INTO tmexamenes (id_exa, fkid_cat, nombre_exa, codigo_exa, costo_exa) VALUES (70, 6, 'Toxoplasmosis IgG Cuantitativa', 'SER-021', 3150.00);

-- ===================== CAMPOS (parámetros) =====================
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (1, 1, 'Hematocrito', '%', '37-47');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (2, 1, 'Hemoglobina', 'g/dL', '12-16');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (3, 1, 'VSG', 'mm/h', 'Hasta 20');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (4, 1, 'Plaquetas', '/mm³', '150.000-450.000');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (5, 1, 'Leucocitos', '/mm³', '4.000-10.000');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (16, 1, 'Coombs Directo', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (17, 1, 'Coombs Indirecto', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (6, 1, 'Neutrófilos', '%', '40-70');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (7, 1, 'Cayados', '%', '0-5');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (8, 1, 'Linfocitos', '%', '20-40');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (9, 1, 'Eosinófilos', '%', '1-4');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (10, 1, 'Monocitos', '%', '2-8');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (11, 1, 'Basófilos', '%', '0-1');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (12, 1, 'Tiempo de Protrombina', 'seg', 'Control 12.1');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (13, 1, 'Tiempo de Tromboplastina', 'seg', 'Control 29.0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (14, 1, 'Actividad Protrombínica', '%', '70-100');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (15, 1, 'INR', '', '0.8-1.2');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (217, 1, 'Razón', '', '0,9-1,2');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (218, 1, 'Tiempo de Coagulación', 'min', '5-10');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (216, 1, 'Tiempo de Sangría', 'min', '1-3');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (18, 2, 'Glicemia', 'mg/dL', '70-110');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (19, 2, 'Colesterol', 'mg/dL', '130-200');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (20, 2, 'Triglicéridos', 'mg/dL', '35-165');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (21, 2, 'Ácido Úrico', 'mg/dL', '2,5-6,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (22, 2, 'Colesterol HDL', 'mg/dL', '35-55');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (23, 2, 'Colesterol LDL', 'mg/dL', 'Hasta 150');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (24, 2, 'Colesterol VLDL', 'mg/dL', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (25, 2, 'Lípidos Totales', 'mg/dL', '400-800');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (26, 2, 'Urea', 'mg/dL', '17,45-45');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (27, 2, 'Creatinina', 'mg/dL', '0,4-1,4');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (28, 2, 'Proteínas Totales', 'g/dL', '6,3-8,5');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (29, 2, 'Albúmina', 'g/dL', '3,5-5,5');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (30, 2, 'Globulina', 'g/dL', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (31, 2, 'Relación A/G', '', '1,2-2,2');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (32, 2, 'Amilasa', 'UA/dL', 'Hasta 90');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (33, 2, 'B.U.N.', 'mg%', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (34, 3, 'Calcio', 'mg/dL', '8,5-10,5');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (35, 3, 'Hierro', 'ug/dL', '60-160');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (36, 3, 'Fósforo', 'mg/dL', '3,0-7,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (37, 3, 'Transaminasa GOT', 'UI/ml', '4-36');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (38, 3, 'Transaminasa GPT', 'UI/ml', '4-32');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (39, 3, 'Gamma GT (mujer)', 'UI/L', '8-35');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (40, 3, 'Gamma GT (hombre)', 'UI/L', '9-54');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (41, 3, 'LDH (mujer)', 'U/L', '103-227');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (42, 3, 'LDH (hombre)', 'U/L', '80-285');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (43, 3, 'Bilirrubina Total', 'mg/dL', '0,4-1,2');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (44, 3, 'Bilirrubina Directa', 'mg/dL', '0,1-0,8');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (45, 3, 'Bilirrubina Indirecta', 'mg/dL', '0,1-0,4');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (46, 3, 'Fosfatasa Ácida', 'U/L', 'Hasta 9,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (47, 3, 'Fosfatasa Alcalina', 'UI/L', '68-240');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (48, 3, 'Fibrinógeno', '%', '200-400');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (49, 3, 'Sodio', 'meq/L', '135-146');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (50, 3, 'Potasio', 'meq/L', '3,5-5,3');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (51, 4, 'Serie Roja', '', 'Descripción');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (52, 4, 'Serie Blanca', '', 'Descripción');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (53, 4, 'Plaquetas', '', 'Descripción');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (54, 5, 'Grupo Sanguíneo', '', 'A / B / AB / O');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (55, 5, 'Factor Rh', '', 'Positivo / Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (56, 6, 'Aspecto', '', 'Transparente');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (57, 6, 'Color', '', 'Amarillo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (58, 6, 'Densidad', '', '1.005-1.030');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (59, 6, 'pH', '', '5,0-7,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (61, 6, 'Albúmina', '', 'Negativa');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (65, 6, 'Hemoglobina', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (60, 6, 'Cetonas', '', 'Negativa');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (62, 6, 'Urobilina', '', 'Negativa');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (66, 6, 'Pigmentos Biliares', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (64, 6, 'Nitritos', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (63, 6, 'Glucosa', '', 'Negativa');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (67, 6, 'Leucocitos (sedimento)', '/campo', '0-5');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (68, 6, 'Hematíes (sedimento)', '/campo', '0-2');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (69, 6, 'Células Epiteliales', '', 'Escasas');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (70, 6, 'Bacterias', '', 'Escasas');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (71, 6, 'Cilindros Granulosos', '', 'Ausentes');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (72, 6, 'Cristales', '', 'Ausentes');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (73, 6, 'Moco', '', 'Escaso');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (74, 6, 'Piocitos', '', 'Ausentes');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (75, 7, 'Aspecto', '', 'Homogéneo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (76, 7, 'Color', '', 'Marrón');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (77, 7, 'Consistencia', '', 'Formada');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (78, 7, 'Hb', '', 'Negativa');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (79, 7, 'Moco', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (80, 7, 'pH', '', '7,0-8,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (81, 7, 'Reacción', '', 'Alcalina');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (82, 7, 'Bacterias', '', 'Escasas');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (83, 7, 'Levaduras', '', 'Ausentes');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (84, 7, 'Azúcares Reductores', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (85, 7, 'Sangre Oculta', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (86, 7, 'Sudán III', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (87, 7, 'Polimorfonucleares', '', 'Escasos');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (88, 7, 'Restos Alimenticios', '', 'Escasos');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (89, 7, 'Parásitos', '', 'No se observan');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (90, 8, 'Salmonella Typhi H', '', 'Negativo (< 1/80)');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (91, 8, 'Salmonella H Para Typhi A', '', 'Negativo (< 1/80)');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (92, 8, 'Salmonella H Para Typhi B', '', 'Negativo (< 1/80)');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (93, 8, 'Salmonella Typhi O', '', 'Negativo (< 1/80)');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (94, 8, 'Salmonella O Para Typhi A', '', 'Negativo (< 1/80)');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (95, 8, 'Salmonella O Para Typhi B', '', 'Negativo (< 1/80)');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (96, 8, 'Brucella Abortus', '', 'Negativo (< 1/80)');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (97, 8, 'Proteus OX-19', '', 'Negativo (< 1/80)');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (98, 9, 'V.D.R.L.', '', 'No Reactivo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (99, 9, 'H.I.V. 1', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (100, 9, 'H.I.V. 2', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (101, 9, 'Anti-Core', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (102, 9, 'Antígeno de Superficie', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (103, 9, 'Serología de Chagas', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (104, 9, 'Hepatitis C', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (105, 10, 'Título ASTO (Antiestreptolisina O)', '', '< 200 Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (106, 10, 'Proteína C Reactiva', '', 'Negativa');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (107, 10, 'R.A. Test', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (108, 10, 'Células L.E.', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (109, 10, 'Monotest', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (110, 11, 'Resultado', '', 'Positiva / Negativa');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (111, 12, 'Observación Directa', '', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (112, 12, 'Tinción de Gram', '', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (113, 12, 'Recuento de Colonias', 'UFC/ml', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (114, 12, 'Otros', '', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (115, 12, 'Cultivo', '', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (116, 12, 'Cultivo para Hongos', '', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (117, 13, 'Hepatitis A (IgM)', 'DO', 'Negativo < 0,90 / Positivo > 1,10');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (118, 14, 'Antígeno de Superficie de Hepatitis B (HBsAg)', '', 'Negativa / Positiva');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (119, 15, 'Anticuerpos Anti-HCV (Hepatitis C)', '', 'Negativo / Positivo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (120, 16, 'Mycoplasma Pneumoniae (IgG)', NULL, 'Positivo / Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (121, 17, 'Gonadotropina Coriónica (Beta-HCG)', 'mIU/ml', '1 sem: 5,00-30,0 | 2 sem: 10,0-71,2 | 3 sem: 30,0-100,0 | 4 sem: 94,0-750,0 | 5 sem: 217,0-7.138 | 6 sem: 350,0-31.795 | 7 sem: 3.697-163.563 | 8 sem:');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (122, 18, 'LH', 'mUI/ml', 'Fase folicular: 1,68-15 | Pico ovulatorio: 21,9-56,6 | Fase lútea: 0,61-16,3 | Post-menopausia: 14,2-52,3');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (123, 19, 'Progesterona', 'ng/ml', 'Fase folicular: 0,15-1,4 | Fase lútea: 4,0-25,0 | Post-menopáusica: 0,06-1,60');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (124, 20, 'Prolactina', 'ng/ml', 'Mujeres: 3,0-23,0 | Hombres: 2,0-17,0 | Mujeres embarazadas: 95-430');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (125, 21, 'pH', '', '3,8-4,5');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (126, 21, 'Aminas', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (127, 21, 'Células', '', 'Regular cantidad');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (128, 21, 'Leucocitos', '', 'Escasos');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (129, 21, 'Bacterias', '', 'Escasas');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (130, 21, 'Hematíes', '', 'Escasos');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (131, 21, 'Levaduras', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (175, 21, 'Reacción polimorfonuclear', '', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (176, 21, 'Células guía', '', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (177, 21, 'Cocobacilos Gram variables tipo', '', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (178, 21, 'Gardenella vaginalis', '', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (133, 22, 'V.D.R.L.', '', 'No Reactivo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (134, 22, 'H.I.V. 1/2', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (135, 23, 'Insulina Basal', 'uIU/ml', 'Niños menores de 12 años: hasta 10,0 | Adultos normales: 0,7-24,9');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (136, 23, 'Insulina Post-Prandial', 'uIU/ml', 'Niños menores de 12 años: hasta 10,0 | Adultos normales: 0,7-24,9');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (137, 24, 'Marihuana', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (138, 24, 'Cocaína', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (139, 25, 'IgM Dengue', '', 'Negativa');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (140, 25, 'IgG Dengue', '', 'Negativa');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (141, 26, 'Inmunoglobulina E', 'IU/ml', '0-1 año: hasta 29 | 1-2 años: hasta 49 | 2-3 años: hasta 45 | 3-9 años: hasta 52 | Adultos: hasta 110');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (142, 27, 'PSA Total', 'ng/ml', 'Hasta 4,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (143, 27, 'PSA Libre', 'ng/ml', '0,00-1,30');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (144, 27, 'Relación % PSA Libre/Total', '%', '');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (145, 28, 'T3', 'ng/ml', '0,8-2,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (146, 28, 'T4', 'ug/dL', '5,0-12,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (147, 28, 'TSH Ultra', 'uIU/ml', '0,4-4,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (148, 29, 'Fosa Derecha', '%', '0,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (149, 29, 'Fosa Izquierda', '%', '0,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (150, 30, 'Eosinófilos en Sangre', 'xmm³', '20-300');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (151, 31, 'IgM Anti-Toxoplasmosis (Método Elisa)', 'DO', 'Negativo < 0,90 / Positivo > 1,10');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (152, 31, 'IgG Anti-Toxoplasmosis', 'DO', 'Negativo < 0,90 / Positivo > 1,10');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (153, 32, 'IgM Anti-Citomegalovirus', 'DO', 'Negativo < 0,90 / Positivo > 1,10');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (154, 32, 'IgG Anti-Citomegalovirus', 'DO', 'Negativo < 0,90 / Positivo > 1,10');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (155, 33, 'Glicemia Basal', 'mg/dL', '70-110');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (156, 33, 'Glicemia 60 min', 'mg/dL', '< 180');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (157, 33, 'Glicemia 120 min', 'mg/dL', '< 140');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (158, 34, 'Testosterona Libre', 'pg/ml', 'Varones prepúberes: 1,80-5,68 | Hombres 20-39 años: 9,2-34,6 | Hombres 40-59 años: 6,1-30,3 | Hombres > 60 años: 6,1-27,9');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (159, 34, 'Testosterona Total', 'ng/ml', 'Mujeres: 0,26-1,22 | Hombres: 2,50-14,6');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (160, 35, 'Helicobacter Pylori', 'DO', 'Positivo > 1,10 DO | Negativo < 0,90 DO');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (163, 37, 'Monotest (Aglutinación)', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (164, 38, 'H.I.V. 1/2 (Test-Pack)', '', 'Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (165, 39, 'Anti TPO', 'IU/ml', 'Hasta 5');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (166, 39, 'Anti TGB', 'IU/ml', 'Hasta 125');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (167, 40, 'Baciloscopia No. 1', '', 'OPC:NO SE ENCUENTRAN B.A.A.R EN 100 CAMPOS MICROSCOPICOS OBSERVADOS | SE ENCUENTRAN B.A.A.R EN 100 CAMPOS MICROSCOPICOS OBSERVADOS');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (168, 40, 'Baciloscopia No. 2', '', 'OPC:NO SE ENCUENTRAN B.A.A.R EN 100 CAMPOS MICROSCOPICOS OBSERVADOS | SE ENCUENTRAN B.A.A.R EN 100 CAMPOS MICROSCOPICOS OBSERVADOS');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (169, 40, 'Baciloscopia No. 3', '', 'OPC:NO SE ENCUENTRAN B.A.A.R EN 100 CAMPOS MICROSCOPICOS OBSERVADOS | SE ENCUENTRAN B.A.A.R EN 100 CAMPOS MICROSCOPICOS OBSERVADOS');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (179, 41, 'Dengue NS1 (Antígeno)', '', 'Positivo / Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (180, 42, 'Hepatitis A (IgM)', 'DO', 'Negativo < 0,90 / Positivo > 1,10');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (181, 43, 'Helicobacter Pylori en Heces', '', 'Positivo / Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (182, 44, 'Estradiol', 'pg/ml', 'Fase folicular temprana: 30-100 | Fase folicular tardía: 100-400 | Fase lútea: 60-150 | Post-menopausia: <18');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (183, 45, 'FSH', 'mIU/ml', 'Fase folicular: 3,0-12,0 | Mitad del ciclo: 8,0-22,0 | Fase lútea: 2,0-12,0 | Post-menopausia: 35,0-151,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (191, 46, 'Chagas', '', 'Positivo / Negativo');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (210, 47, 'Antígeno Carcinoembrionario', 'ng/ml', 'Fumadores: 0,00-4,3 | No fumadores: 0,00-3,40');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (203, 48, 'CA 19-9', 'UI/ml', 'Hasta 35 UI/ml');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (194, 49, 'CA-125', 'UI/ml', 'Hasta 35,0 UI/ml');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (200, 50, 'CA 15-3', 'UI/ml', 'Hasta 35 UI/ml');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (196, 51, 'Alfafetoproteínas', 'IU/ml', 'Hasta 5,80');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (192, 52, '17 OH Progesterona', 'ng/ml', 'Fase folicular: 0,1-1,7 | Fase luteínica: 0,6-2,3 | Postmenopausia: 0,13-0,51');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (207, 53, 'DHEA', 'ug/dl', '33,9-280');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (193, 54, 'Androstenediona', 'ng/ml', '0,40-4,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (205, 55, 'IgM Anti-Virus del Epstein Barr', 'U/ml', 'Negativo < 0,90 / Positivo > 1,10');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (197, 56, 'Hemoglobina A1c', '%', '4,5-6,3');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (188, 57, 'Fibrinógeno', 'mg%', '200-400');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (187, 58, 'TSH Ultra', 'uIU/ml', '0,4-5,5');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (202, 59, 'Microalbuminuria', 'mg/lts', 'Hasta 20,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (199, 60, 'ANA', 'DO', 'Negativo < 0,90 / Positivo > 1,10');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (208, 61, 'LDH', 'U/L', '230-460');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (209, 62, 'Anti-HBs', 'mIU/ml', 'Vacunación: > 10 | Negativo: < 9,9');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (184, 63, 'IgG Anti Varicela Zoster', '', 'Negativo: < 9,0 | Borderline: 9,0-11,0 | Positivo: > 11,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (198, 64, 'Dímero-D', 'ng/ml', 'Hasta 200,0');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (190, 65, 'Herpes I IgG', 'U/ml', 'Negativo < 0,90 / Positivo > 1,10');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (201, 65, 'Herpes II IgM', 'U/ml', 'Negativo < 0,90 / Positivo > 1,10');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (195, 66, 'CPK', 'U/L', '195');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (185, 67, 'Vitamina D', 'ng/ml', 'Deficiente: <10 | Insuficiente: 10-30 | Suficiente: 30-100 | Intoxicación: >100');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (186, 68, 'Cortisol 7 AM', 'nmol/l', '140-600');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (189, 68, 'Cortisol 3 PM', 'nmol/l', '68-237');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (204, 69, 'Mycoplasma Pneumoniae IgM', 'DO', 'Positiva > 1,10 DO / Negativa < 0,90 DO');
INSERT INTO tmcampos (id_cam, fkid_exa, nombre_cam, unidad, referencia) VALUES (206, 70, 'Toxoplasmosis IgG', 'mg/dl', '90-450');
